#+HTML_DOCTYPE: html5
#+OPTIONS: toc:nil num:nil html5-fancy:t
#+MACRO: begin-block #+HTML: <div class="$1">
#+MACRO: end-block #+HTML: </div>

{{{begin-block(Page)}}}


* Кружок в ФМЛ

В Кировском физико-математическом лицее идёт кружок по
программированию.  Цель — изучение алгоритмов и структур данных,
участие в олимпиадах по информатике. Занятия состоят из лекций и
практики решения задач на ЭВМ.  Предполагается, что школьник уже
владеет хотя бы одним языком программирования на базовом уровне
(переменные, арифметические операции, условный оператор, циклы,
массивы).

Присоединиться к кружку может любой желающий. Занятия бесплатные и
проводятся для учащихся всех школ города (не только лицея).

** Расписание

Осенью 2014 года занятия начинаются в следующее время:

+ Среда, 14-00 :: Занятие для победителей и призеров регионального
                  этапа.
+ Пятница, 15:00 :: Лекция для занимающихся второй год.
+ Пятница, 15:45 :: Лекция для новичков.

Все занятия проходят в 14-м кабинете.

** Контакты

Занятия проводит Пестов Олег Александрович. Телефон: +7(909)143-5774,
адрес электронной почты: ~oleg.pestov@gmail.com~.
В сети ВКонтакте есть [[http://vk.com/club76865834][группа]] с актуальными новостями и объявлениями.

** Адрес

КОГОАУ «Кировский физико-математический лицей», г. Киров, ул. Труда 16.

{{{end-block}}}
