#+HTML_DOCTYPE: html5
#+OPTIONS: toc:nil num:nil html5-fancy:t
#+MACRO: begin-block #+HTML: <div class="$1">
#+MACRO: end-block #+HTML: </div>

{{{begin-block(Page)}}}

* Четвёртая командная олимпиада по программированию Ёjik

*17 мая 2015 года* состоится четвёртая командная олимпиада по
программированию Ёjik (произносится «ёжик»).
Это командное соревнование, которое проводится в один компьютерный тур
продолжительностью 3 часа. Команде из трёх человек предоставляется один
персональный компьютер и предлагается решить несколько задач. Для решения
участники могут использовать следующие языки программирования: C/C++, C#,
Java, Pascal, Python.

Задачи олимпиады рассчитаны на самый широкий круг участников: они в
большинстве своем доступны школьникам, не овладевшим целиком основами
языка программирования (например, школьникам, не владеющим строками
или двумерными массивами, будут доступны большинство задач).

Понять уровень олимпиады можно посмотрев материалы прошедших
соревнований:

+ [[./2013.html][Осень 2013 года]]
+ [[./2014s.html][Весна 2014 года]]
+ [[./2014a.html][Осень 2014 года]]

** [[http://ejudge.oplab.org/cgi-bin/new-client?contest_id%3D77&locale_id%3D1][Вход в проверяющую систему]]
** [[./2015s-statements.pdf][Условия задач]]
** [[./tests-fake.zip][Тесты для третьей задачи]]
** [[http://school.oplab.org/standings.html][Текущие результаты]]

** Регистрация

Для участия в турнире необходимо до 15 мая отправить письмо по адресу
~oleg.pestov@gmail.com~. В письме необходимо указать:

+ учебное заведение (если участники представляют разные учебные заведения, то укажите все)
+ название команды
+ состав команды (для каждого школьника укажите фамилию, имя и класс)
+ необходимое программное обеспечение (например: PascalABC.NET, CodeBlocks 12.04)

Кроме того, если вы участвуете дистанционно **и** хотите получить оригиналы
дипломов, то укажите почтовый адрес на который их следует отправить (индекс,
адрес, получатель).

** Правила олимпиады

+ В олимпиаде принимают участие команды, каждая из которых составлена из трёх
  школьников.
+ Олимпиада проводится в один компьютерный тур. На туре команде предоставляется
  персональный компьютер и предлагается решить несколько
  задач. Продолжительность тура — 3 часа.
+ Во время тура разрешается пользоваться любой литературой и личными
  записями. Запрещается использовать любую информацию в электронном виде, а
  также технику, за исключением предоставляемого компьютера.
+ Во время тура участники решают предложенные задачи. Решением задачи является
  программа, составленная на одном из допустимых языков
  программирования. Программа не должна содержать вспомогательных модулей или
  файлов. Разные задачи можно решать на разных языках программирования.
+ Все задачи предполагают, что входные данные поступают из стандартного потока
  ввода («ввод с клавиатуры»), а результаты должны быть выведены в стандартный
  поток вывода («вывод на экран»).
+ Проверка решений производится во время соревнований. По мере готовности,
  решения сдаются в автоматизированную тестирующую систему. Программа
  проверяется в течение нескольких минут, на заранее подготовленном жюри,
  одинаковом для всех участников наборе тестов. После того, как решение будет
  проверено, команда получает сообщение с результатами тестирования.
+ Оценка решения зависит от пройденных тестов. Тесты разбиты на группы. Если все
  тесты группы пройдены, то к баллам за задачу прибавляется стоимость данной
  группы.  Если хотя бы один тест из группы не пройден, то баллы за неё не
  начисляются. Максимальная оценка за все задачи — 100 баллов.  Кроме этого, за
  каждую посылку частично верного или неверного решения снимается один
  балл. Количество баллов за задачу не бывает отрицательным.
+ Побеждает команда, набравшая больше всего баллов.
+ Во всех задачах требуется написать консольное приложение. Время тестирования
  решения и доступная память на каждом тесте ограничены (как правило 1 секунда и
  64 мегабайта). Решения, превысившие установленное ограничение, считаются
  неэффективными для данной задачи. В этом случае тест считается не
  пройденным. Жюри указывает ограничения на время работы программы на одном
  тесте и на размер доступной памяти в формулировках задач.
+ Во время тура участники могут общаться только с членами своей команды и
  представителями жюри.
+ За нарушение правил олимпиады команда может быть дисквалифицирована.

{{{end-block}}}

** Место очного проведения

КОГОАУ «Кировский физико-математический лицей», г. Киров, ул. Труда 16.

** Расписание

*17 мая 2015 года:*

+ 9:30 - 10:00 :: открытие, объяснение правил
+ 10:00 - 13:00 :: cоревнование
+ 13:00 :: подведение итогов

** Жюри олимпиады

+ Ашихмин Анатолий Александрович КОГОАУ КФМЛ, г. Киров
+ Будин Николай Алексеевич, КОГОАУ КФМЛ, г. Киров
+ Бураков Иван Александрович, Лицей, г. Кирово-Чепецк
+ Дехтерев Кирилл Евгеньевич, КОГОАУ КФМЛ, г. Киров
+ Кайсин Илья Сергеевич, КОГОАУ КФМЛ, г. Киров
+ Латышев Алексей Сергеевич, НИУ ИТМО, г. Санкт-Петербург
+ Пестов Олег Александрович, КОГОАУ КФМЛ, г. Киров
+ Радаев Вадим Александрович, КОГОАУ КФМЛ, г. Киров

** Организационный комитет

+ Пестов Олег Александрович, КОГОАУ КФМЛ, г. Киров
+ Щепин Тимофей Аркадьевич, КОГОАУ КФМЛ, г. Киров
+ Ямбарышева Светлана Юрьевна, КОГОАУ КФМЛ, г. Киров

** Контакты

Пестов Олег Александрович, +7(909)143-5774, ~oleg.pestov@gmail.com~.
