#+HTML_DOCTYPE: html5
#+OPTIONS: toc:nil num:nil html5-fancy:t
#+MACRO: begin-block #+HTML: <div class="$1">
#+MACRO: end-block #+HTML: </div>

{{{begin-block(Page)}}}

* ЯНАО, региональный этап РОИ 2014/2015

| Первый тур. Дорешивание |         | [[http://ejudge.oplab.org/cgi-bin/new-client?contest_id%3D000066&locale_id%3D1][Вход]] |
| **Первый тур**          |         | [[http://ejudge.oplab.org/cgi-bin/new-client?contest_id%3D000064&locale_id%3D1][Вход]] |
| Пробный тур             | [[./region_training.pdf][Условия]] | [[http://ejudge.oplab.org/cgi-bin/new-client?contest_id%3D000060&locale_id%3D1][Вход]] |
| Командная олимпиада     |         | [[http://ejudge.oplab.org/cgi-bin/new-client?contest_id%3D000061&locale_id%3D1][Вход]] |
| Вложенные циклы         | [[http://ejudge.oplab.org/05-nested-loops/statements.html][Условия]] | [[http://ejudge.oplab.org/cgi-bin/new-client?contest_id%3D0000062&locale_id%3D1][Вход]] |
| Одномерные массивы      | [[http://ejudge.oplab.org/06-arrays-1d/statements.html][Условия]] | [[http://ejudge.oplab.org/cgi-bin/new-client?contest_id%3D000063&locale_id%3D1][Вход]] |

** Изменения в процедуре проверки

Обращаем внимание, что в этом году существенно изменились требования по проверке и оцениванию решений участников.

+ Сданное решение проверяется на тестах из условия, участникам доступен полный
  протокол проверки на тестах из условия. Если решение не проходит хотя бы один
  тест из условия, оно оценивается в 0 баллов. Если решение проходит все тесты
  из условия, то оно получает статус «Принято на проверку», при этом сразу же
  проводится проверка сданного решения на всех тестах, но результат этой
  проверки не сообщается участнику.

+ Условия каждой задачи разбиваются на несколько отдельных подзадач
  отличающихся, как правило, ограничениями на размер входных данных или разными
  частными случаями формулировки задачи. Каждой подзадаче соответствует своя
  группа тестов. Баллы за каждую подзадачу могут начисляться либо отдельно за
  каждый тест (тогда сумма баллов за подзадачу равна сумме баллов за успешно
  пройденные тесты), или за всю задачу целиком баллы при условии прохождения
  всех тестов данной группы (если хотя бы один из тестов группы не пройден, то
  баллы за группу не начисляются).

+ По каждой задаче участник может не более 10 раз в течение тура получить
  результат проверки решений на всех тестах. В этом случае участнику сообщается
  результат проверки сданного решения на всех тестах. Характер сообщаемой
  информации о результатах проверки указан в условии задачи и может быть
  следующим: либо участнику сообщается только количество набранных баллов в
  каждой подзадаче (без детализации результатов тестирования на каждом тесте),
  либо участнику сообщается результат проверки задачи на каждом тесте (тест
  пройден, неверный ответ, неверный формат вывода результата, превышение времени
  работы программы, превышение ограничения по памяти, ошибка исполнения
  программы, нарушение правил безопасности). Описание того, какая информация о
  результатах проверки решения сообщается участнику по запросу, содержится в
  условии каждой задачи.

+ Если участник использовал все 10 запросов результата по какой-то задаче, то он
  всё равно может отправлять решения этой задачи, но не имеет возможности
  запросить результаты проверки решения данной задачи на всех тестах.

+ Итоговый балл по каждой задаче определяется, как максимум из следующих двух
  значений: максимального балла за те сданные решения, по которым участником был
  запрошен протокол проверки, и баллом последнего решения, принятого на
  проверку.

{{{end-block}}}
